package view;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Projet Java - Calculator - Calculadora
 *
 * @author Raul HERNANDEZ
 */
public class Calculator extends javax.swing.JFrame {

    private String numbers = "";
    private String operation = "nula";
    private double number1, result;
    private boolean active = true;
    private boolean point = true;
    private boolean on = false;

    /**
     * Creates new form NewJFrame
     */
    public Calculator() {
        initComponents();
        this.setTitle("Projet Java - Calculator");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btn_ce = new javax.swing.JButton();
        btn_onc = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_percentage = new javax.swing.JButton();
        btn_squareRoot = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_multiplication = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        btn_subtraction = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_point = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_equal = new javax.swing.JButton();
        lbl_num = new javax.swing.JLabel();
        lbl_show = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridLayout(5, 5));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("MRC");
        panel.add(jButton1);

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton11.setText("M+");
        panel.add(jButton11);

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setText("M-");
        panel.add(jButton10);

        btn_ce.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ce.setText("CE");
        btn_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceActionPerformed(evt);
            }
        });
        panel.add(btn_ce);

        btn_onc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_onc.setText("ON-C");
        btn_onc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oncActionPerformed(evt);
            }
        });
        panel.add(btn_onc);

        btn_7.setBackground(new java.awt.Color(102, 102, 102));
        btn_7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        panel.add(btn_7);

        btn_8.setBackground(new java.awt.Color(102, 102, 102));
        btn_8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        panel.add(btn_8);

        btn_9.setBackground(new java.awt.Color(102, 102, 102));
        btn_9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        panel.add(btn_9);

        btn_percentage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_percentage.setText("%");
        btn_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_percentageActionPerformed(evt);
            }
        });
        panel.add(btn_percentage);

        btn_squareRoot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_squareRoot.setText("√");
        btn_squareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_squareRootActionPerformed(evt);
            }
        });
        panel.add(btn_squareRoot);

        btn_4.setBackground(new java.awt.Color(102, 102, 102));
        btn_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        panel.add(btn_4);

        btn_5.setBackground(new java.awt.Color(102, 102, 102));
        btn_5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        panel.add(btn_5);

        btn_6.setBackground(new java.awt.Color(102, 102, 102));
        btn_6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        panel.add(btn_6);

        btn_multiplication.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_multiplication.setText("X");
        btn_multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicationActionPerformed(evt);
            }
        });
        panel.add(btn_multiplication);

        btn_division.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_division.setText("/");
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        panel.add(btn_division);

        btn_1.setBackground(new java.awt.Color(102, 102, 102));
        btn_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        panel.add(btn_1);

        btn_2.setBackground(new java.awt.Color(102, 102, 102));
        btn_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        panel.add(btn_2);

        btn_3.setBackground(new java.awt.Color(102, 102, 102));
        btn_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        panel.add(btn_3);

        jButton24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton24.setText("X²");
        panel.add(jButton24);

        btn_subtraction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_subtraction.setText("-");
        btn_subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subtractionActionPerformed(evt);
            }
        });
        panel.add(btn_subtraction);

        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton23.setText("+/-");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        panel.add(jButton23);

        btn_0.setBackground(new java.awt.Color(102, 102, 102));
        btn_0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        panel.add(btn_0);

        btn_point.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_point.setText(".");
        btn_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pointActionPerformed(evt);
            }
        });
        panel.add(btn_point);

        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_add.setText("+");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        panel.add(btn_add);

        btn_equal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_equal.setText("=");
        btn_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalActionPerformed(evt);
            }
        });
        panel.add(btn_equal);

        lbl_num.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_num.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbl_show.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_show.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_show, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_num, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("7");
            System.out.println(numbers);
            System.out.println("type Numbers: "+((Object)numbers).getClass().getSimpleName());
        }
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("8");
        }
        active = true;
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("9");
        }
        active = true;
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("4");
        }
        active = true;
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("5");
        }
        active = true;
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("6");
        }
        active = true;
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("1");
        }
        active = true;
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("2");
        }
        active = true;
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("3");
        }
        active = true;
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        if (on == true) {          //the calculator is active
            addNumber("0");
        }
        active = true;
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (active == true) {
            number1 = Double.parseDouble(numbers);      //convert the string variable numbers to double
            System.out.println(number1);
            System.out.println("btn + --> Number1: "+((Object)number1).getClass().getSimpleName());
            lbl_show.setText(numbers + " + ");
            numbers = "";
            System.out.println("btn + --> numbers: " + numbers);
            operation = "addition";
            System.out.println("operation = " + operation);

            active = false;
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalActionPerformed
        double number2;
        switch (this.operation) {
            case "nula":
                lbl_num.setText(numbers);
                break;
            case "addition":
                number2 = Double.parseDouble(numbers);     //convert the string variable numbers to double
                System.out.println("= addition --> number2: " + number2);
                System.out.println("= addition type --> number2: "+((Object)number2).getClass().getSimpleName());
                result = number1 + number2;
                System.out.println("= result F --> number OPE: " + result);
                System.out.println("= addition type --> result: "+((Object)result).getClass().getSimpleName());
                lbl_num.setText(String.format("%.2f", result).replace(',', '.'));           //set lbl_num
                numbers = String.valueOf(this.result);          //convert to string
                System.out.println("= numbers F --> number: " + numbers);
                System.out.println("= addition type --> numbers: "+((Object)numbers).getClass().getSimpleName());
                this.operation = "nula";
                break;
            case "subtraction":
                number2 = Double.parseDouble(numbers);     //convert the string variable numbers to double
                this.result = (this.number1 - number2);
                lbl_num.setText(String.format("%.2f", this.result).replace(',', '.'));           //set lbl_num
                numbers = String.valueOf(this.result);          //convert to string
                this.operation = "nula";
                break;
            case "multiplication":
                number2 = Double.parseDouble(numbers);     //convert the string variable numbers to double
                this.result = (this.number1 * number2);
                lbl_num.setText(String.format("%.2f", this.result).replace(',', '.'));           //set lbl_num
                numbers = String.valueOf(this.result);          //convert to string
                this.operation = "nula";
                break;
            case "division":
                number2 = Double.parseDouble(numbers);     //convert the string variable numbers to double
                if (number2 == 0) {
                    lbl_num.setText("We can't divide by zero");
                    break;
                } else {
                    this.result = (this.number1 / number2);
                    lbl_num.setText(String.format("%.2f", this.result).replace(',', '.'));           //set lbl_num
                    numbers = String.valueOf(this.result);          //convert to string
                    this.operation = "nula";
                    break;
                }
            default:
                break;
        }
        lbl_show.setText("");
        this.active = false;
    }//GEN-LAST:event_btn_equalActionPerformed

    private void btn_multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicationActionPerformed
        if (active == true) {
            number1 = Double.parseDouble(numbers);      //convert the string variable numbers to double
            System.out.println(number1);
            lbl_show.setText(numbers + " x ");
            numbers = "";
            operation = "multiplication";

            active = false;

        }
    }//GEN-LAST:event_btn_multiplicationActionPerformed

    private void btn_subtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subtractionActionPerformed
        if (active == true) {
            number1 = Double.parseDouble(numbers);      //convert the string variable numbers to double
            lbl_show.setText(numbers + " - ");
            numbers = "";
            operation = "subtraction";

            active = false;

        }
    }//GEN-LAST:event_btn_subtractionActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        if (active == true) {
            number1 = Double.parseDouble(numbers);      //convert the string variable numbers to double
            lbl_show.setText(numbers + " / ");
            numbers = "";
            operation = "division";

            active = false;

        }
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_squareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_squareRootActionPerformed
        number1 = Double.parseDouble(numbers);
        lbl_show.setText("sqrt(" + number1 + ")");
        this.result = Math.sqrt(number1);
        lbl_num.setText(String.format("%.2f", this.result));
        numbers = String.valueOf(this.result);

    }//GEN-LAST:event_btn_squareRootActionPerformed

    private void btn_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pointActionPerformed
        if (point == true) {
            if (numbers.equals("0")) {
                numbers = "0.";
            } else {
                numbers += ".";
            }
            lbl_num.setText(numbers);
            point = false;
        }
    }//GEN-LAST:event_btn_pointActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        if (numbers.charAt(0) != '-') {
            numbers = '-' + numbers;
        } else {
            numbers = numbers.substring(1, numbers.length());
        }
        lbl_num.setText(numbers);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void btn_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceActionPerformed

    }//GEN-LAST:event_btn_ceActionPerformed

    private void btn_oncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oncActionPerformed
        if (lbl_num.getText().equals("") && lbl_show.getText().equals("") && on != true) {
            onCalculator();
        } else {
            lbl_show.setText("");
            lbl_num.setText("0");
            operation = "nula";
            numbers = "";
            on = true;
            active = true;
            point = true;

        }

    }//GEN-LAST:event_btn_oncActionPerformed

    private void btn_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_percentageActionPerformed
        // testttt btn igual

    }//GEN-LAST:event_btn_percentageActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.InstantiationException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    public void onCalculator() {
        lbl_num.setText("0");
        lbl_show.setText("Welcome Kevin");
        on = true;
    }

    /**
     * add number to calculator
     *
     * @param num
     */
    public void addNumber(String num) {
        if (lbl_num.getText().equals("0")) {
            numbers = num;
        } else {
            numbers += num;
        }
        lbl_num.setText(numbers);
//        lbl_num.setText(lbl_num.getText() + num);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_ce;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_equal;
    private javax.swing.JButton btn_multiplication;
    private javax.swing.JButton btn_onc;
    private javax.swing.JButton btn_percentage;
    private javax.swing.JButton btn_point;
    private javax.swing.JButton btn_squareRoot;
    private javax.swing.JButton btn_subtraction;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_num;
    private javax.swing.JLabel lbl_show;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
